### PR TITLE
squid:S2131 - Primitives should not be boxed just for String conversion

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S2131 - Primitives should not be boxed just for String conversion

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2131

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by ctron** [comment]
Looks good to me! Only one minor thing I overlooked earlier. Could you please use the code style as described in [1]. There are code formatter settings which can automatically be applied. Thanks! :+1: 

[1] https://eclipse.org/package-drone/development.php

**Comment by ctron** [comment]
I think there is still something wrong. See all the copyright headers, how they did get formatted. Also there are some new line breaks added, which don't get added when I apply the code formatter.

How did you apply the code formatter? And which version of Eclipse are you using?

**Comment by m-ezzat** [comment]
I've tried it once again, and I imported the eclipse_formatter.xml file using Kepler Service Release 1 version.

The previous time was using a different IDE, it's shown that it was the reason, but now I see a white space after those *, Let me know if this should be handled manually, please. Thanks!

**Comment by ctron** [comment]
Seems fine now. I will merge it later.

I would recommend using Mars.2 instead of Kepler. Kepler is quite old now and there were a few changes to the code formatter engine which might result in the little differences. But don't bother for this one.

**Comment by ctron** [comment]
Thanks for the contribution :+1:

**Pull request merged**
