### PR TITLE
Fix wrong exception message

### PR DESCRIPTION
**Pull request by looperhacks**
These wrong messages could cause an IllegalFormatException.

### CODE REVIEW

**Comment by looperhacks** [comment]
Like this?

**Comment by ctron** [comment]
Thanks for the PR!

**Comment by ctron** [comment]
Let me know how soon you need a new release.

**Comment by looperhacks** [comment]
This wasn't a problem for us, I just noticed it. We don't need a new release just for this.

**Comment by ctron** [comment]
That makes your contribution even more awesome!

**Pull request merged**
